import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { PROVIDERS, checkConfiguration, configPath, hydrateCredentialToProcess, loadCredential, loadNonSecretConfig, redactSecret, redactText, saveCredential, saveNonSecretConfig } from "../agent/src/settings.mjs";

test("terminal credentials remain process-only and all secret forms are redacted", () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "ecomic-settings-"));
  saveNonSecretConfig({ provider: "deepseek", model: "deepseek-chat", base_url: null, tool_calling_verified: true }, home);
  saveCredential("deepseek", "test-deepseek-key-23af");
  saveCredential("openai", "test-openai-key-3456");
  assert.equal(JSON.parse(fs.readFileSync(configPath(home), "utf8")).provider, "deepseek");
  assert.equal(fs.existsSync(path.join(home, ".ecomic", "credentials.env")), false);
  assert.equal(loadCredential("deepseek"), "test-deepseek-key-23af");
  assert.equal(hydrateCredentialToProcess("openai"), "test-openai-key-3456");
  assert.equal(process.env.OPENAI_API_KEY, "test-openai-key-3456");
  assert.equal(loadNonSecretConfig(home).tool_calling_verified, true);
  assert.equal(redactSecret("test-deepseek-key-23af"), "tes****23af");
  assert.equal(redactText("Authorization: Bearer super-secret"), "Authorization: Bearer [REDACTED]");
  assert.equal(redactText("token=super-secret"), "token=[REDACTED]");
  assert.equal(checkConfiguration({ provider: "deepseek", model: "deepseek-chat" }, "key").ok, true);
  assert.equal(checkConfiguration({ provider: "custom_openai_compatible", model: "m", base_url: "https://example.test" }, "key").ok, true);
  assert.equal(PROVIDERS.google.keyEnv, "GEMINI_API_KEY");
  assert.equal(PROVIDERS.minimax.keyEnv, "MINIMAX_API_KEY");
  assert.equal(PROVIDERS.qwen.piProvider, "qwen-token-plan-cn");
  delete process.env.DEEPSEEK_API_KEY;
  delete process.env.OPENAI_API_KEY;
  fs.rmSync(home, { recursive: true, force: true });
});
