import { useEffect, useState } from "react";
import { Activity, BarChart3, Bot, Database, FileText, FlaskConical, History, Moon, PanelLeft, PlusCircle, Settings, Sun } from "lucide-react";
import { DesktopBridge, type DesktopHealth } from "./bridge";

type Page = "home" | "new" | "datasets" | "workbench" | "experiments" | "history" | "providers" | "settings";
const pages: { id: Page; label: string; icon: typeof Activity; hint: string }[] = [
  { id: "home", label: "首页", icon: Activity, hint: "概览、后端状态与继续研究" }, { id: "new", label: "新建研究", icon: PlusCircle, hint: "导入数据并创建新的科研 Session" }, { id: "datasets", label: "数据集", icon: Database, hint: "查看导入数据的概要与语义候选" }, { id: "workbench", label: "科研工作台", icon: FlaskConical, hint: "数据环境、研究时间线与当前证据" }, { id: "experiments", label: "实验记录", icon: BarChart3, hint: "策略运行、轨迹与可见证据" }, { id: "history", label: "历史研究", icon: History, hint: "恢复已持久化的 SQLite Session" }, { id: "providers", label: "模型与 API", icon: Bot, hint: "配置 Provider、模型和安全凭据" }, { id: "settings", label: "系统设置", icon: Settings, hint: "本地运行时与界面设置" }
];
export function App() { const [page, setPage] = useState<Page>("home"); const [dark, setDark] = useState(true); const [compact, setCompact] = useState(false); useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; }, [dark]); const selected = pages.find((item) => item.id === page)!; return <main className={compact ? "app compact" : "app"}><aside className="sidebar" aria-label="主导航"><div className="brand"><span className="brand-mark">E</span>{!compact && <span>ECOMIC <small>DESKTOP</small></span>}<button title="收起导航" onClick={() => setCompact(!compact)}><PanelLeft size={18}/></button></div><nav>{pages.map((item) => { const Icon = item.icon; return <button key={item.id} className={page === item.id ? "nav-item active" : "nav-item"} onClick={() => setPage(item.id)} title={item.label}><Icon size={19}/>{!compact && <span>{item.label}</span>}</button>; })}</nav><div className="sidebar-bottom"><span className="status-dot"/> {!compact && "本地研究模式"}</div></aside><section className="shell"><header className="topbar"><div><p className="eyebrow">ECOMIC Desktop / {selected.label}</p><h1>{selected.label}</h1></div><button className="theme-button" onClick={() => setDark(!dark)} aria-label="切换主题">{dark ? <Sun size={18}/> : <Moon size={18}/>} {dark ? "浅色" : "深色"}</button></header><section className="content" key={page}><PageContent page={page} hint={selected.hint}/></section><footer className="statusbar"><span><span className="status-dot"/> 科研后端：本地 Bridge</span><span>数据库：本地 SQLite</span><span>Agent Host：未启动</span><span className="oracle">Oracle LOCKED</span></footer></section></main>; }
function PageContent({ page, hint }: { page: Page; hint: string }) { if (page === "home") return <><section className="hero"><span className="kicker">选择性标签 · AI for Science</span><h2>把历史决策中的“不可见标签”变成可审计的科研流程。</h2><p>从数据导入、DomainSpec 确认、受控 Scientist Agent，到最终评价与中文报告，全部在一个本地桌面工作区内完成。</p><div className="actions"><button className="primary">新建研究</button><button>恢复历史研究</button></div></section><section className="cards"><HealthCard/><StatusCard title="当前研究" value="尚未选择" note="从“新建研究”导入 CSV / Parquet"/><StatusCard title="最终评价" value="Oracle LOCKED" note="研究阶段不显示 outer metrics"/></section></>; return <section className="placeholder"><p className="kicker">{page.toUpperCase()}</p><h2>{hint}</h2><p>此页面已在桌面导航中就绪。后续模块会将真实研究数据、安全凭据和科研运行过程接入该区域。</p><div className="empty-icon"><FileText size={28}/></div></section>; }
function HealthCard() { const [health, setHealth] = useState<DesktopHealth | null>(null); const [message, setMessage] = useState("通过 Tauri IPC 检查本地 Sidecar"); const [checking, setChecking] = useState(false); const check = async () => { setChecking(true); try { const result = await DesktopBridge.healthCheck(); setHealth(result); setMessage(""); } catch { setHealth(null); setMessage("后端暂不可用，界面仍可继续使用。可稍后重试。"); } finally { setChecking(false); } }; return <article className="card"><p>科研后端</p><h3>{health ? health.backend : "待连接"}</h3><small>{health ? `数据库：${health.database} · Agent Host：${health.agent_host}` : message}</small><button className="primary health-button" onClick={check} disabled={checking}>{checking ? "检查中…" : "后端状态"}</button></article>; }
function StatusCard({ title, value, note }: { title: string; value: string; note: string }) { return <article className="card"><p>{title}</p><h3>{value}</h3><small>{note}</small></article>; }
