import { useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, LoaderCircle } from "lucide-react";
import { DesktopBridge, type DatasetSession } from "./bridge";

type Props = { session: DatasetSession; onConfirmed?: () => void };
const labels = ["历史决策", "可观测值", "隐藏值", "结果", "成本", "时间", "观察动作", "完整 DomainSpec", "人工确认"];
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export function DomainSpecWizard({ session, onConfirmed }: Props) {
  const columns = useMemo(() => Object.keys(session.schema.columns), [session]);
  const candidates = session.candidates;
  const [step, setStep] = useState(0);
  const [decision, setDecision] = useState(candidates.decision?.[0]?.column ?? columns[0] ?? "");
  const [observed, setObserved] = useState(""); const [hidden, setHidden] = useState("");
  const [outcome, setOutcome] = useState(candidates.target?.[0]?.column ?? ""); const [cost, setCost] = useState(candidates.cost?.[0]?.column ?? "");
  const [decisionTime, setDecisionTime] = useState(""); const [outcomeTime, setOutcomeTime] = useState("");
  const [reversible, setReversible] = useState(true); const [simulatable, setSimulatable] = useState(true); const [action, setAction] = useState("");
  const [notice, setNotice] = useState("请逐步确认语义；研究执行在两项人工确认完成前会被后端拒绝。"); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  const select = (label: string, value: string, onChange: (value: string) => void) => <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">未选择</option>{columns.map((column) => <option value={column} key={column}>{column}</option>)}</select></label>;
  const confirm = async () => { setBusy(true); try { const decisionResult = await DesktopBridge.call("confirm_decision_mapping", { session_id: session.session_id, decision_column: decision, observed_values: split(observed), non_observed_values: split(hidden), target_column: outcome || undefined, cost_column: cost || undefined, decision_time: decisionTime || undefined, outcome_time: outcomeTime || undefined }); await DesktopBridge.call("confirm_observation_action", { session_id: session.session_id, reversible, simulatable, description: action }); setNotice(`DomainSpec 已版本化确认。审计状态：${String((decisionResult as any).audit?.status ?? "已提交")}`); setDone(true); onConfirmed?.(); } catch (error) { setNotice(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  const disabled = (step === 0 && !decision) || (step === 1 && !split(observed).length) || (step === 2 && !split(hidden).length) || (step === 3 && !outcome) || step === 8 && (!decision || !split(observed).length || !split(hidden).length || !outcome || !action.trim());
  return <section className="domain-wizard"><div className="provider-heading"><div><p className="kicker">DOMAIN SPEC WIZARD</p><h2>选择性标签业务语义</h2><p>Session：{session.session_id}。每次最终确认都会写入 SQLite 新版本，页面不会要求编辑 JSON。</p></div></div><ol className="wizard-steps">{labels.map((label, index) => <li key={label} className={index === step ? "active" : index < step || done ? "done" : ""}>{index + 1}<span>{label}</span></li>)}</ol><section className="card wizard-card">{step === 0 && <>{select("Step 1 · 历史决策字段", decision, setDecision)}<p>该字段表示历史上是否进行了会影响标签可见性的决策。</p></>}{step === 1 && <label>Step 2 · 哪些决策值表示可获得后续标签？<input value={observed} onChange={(event) => setObserved(event.target.value)} placeholder="例如 1, approved, reviewed（逗号分隔）" /></label>}{step === 2 && <label>Step 3 · 哪些决策值表示标签隐藏？<input value={hidden} onChange={(event) => setHidden(event.target.value)} placeholder="例如 0, rejected, not_reviewed（逗号分隔）" /></label>}{step === 3 && select("Step 4 · 结果/后续标签字段", outcome, setOutcome)}{step === 4 && select("Step 5 · 观察成本字段（可选）", cost, setCost)}{step === 5 && <div className="wizard-grid">{select("Decision time（可选）", decisionTime, setDecisionTime)}{select("Outcome time（可选）", outcomeTime, setOutcomeTime)}</div>}{step === 6 && <><label>Step 7 · 观察动作说明<textarea value={action} onChange={(event) => setAction(event.target.value)} placeholder="例如：对候选样本发起额外审核/检测，以获得后续真实结果" /></label><label><input type="checkbox" checked={reversible} onChange={(event) => setReversible(event.target.checked)} /> 该观察/离线回放动作可逆</label><label><input type="checkbox" checked={simulatable} onChange={(event) => setSimulatable(event.target.checked)} /> 可在当前数据集上模拟</label></>}{step === 7 && <pre className="domain-preview">{JSON.stringify({ decision, observed_values: split(observed), hidden_values: split(hidden), outcome, cost: cost || null, decision_time: decisionTime || null, outcome_time: outcomeTime || null, observation_action: { description: action, reversible, simulatable } }, null, 2)}</pre>}{step === 8 && <><h3>Step 9 · 人工确认</h3><p>确认后会先写入决策映射版本，再写入观察动作版本。未确认任一项时，后端会拒绝开始实验。</p>{done && <p className="connection-result success"><CheckCircle2 size={16}/> 已确认，可进入科研工作台。</p>}</>}<p className="form-notice" role="status">{notice}</p><div className="form-actions"><button disabled={busy || step === 0} onClick={() => setStep(step - 1)}><ChevronLeft size={16}/> 上一步</button>{step < 8 ? <button className="primary" disabled={busy || disabled} onClick={() => setStep(step + 1)}>下一步 <ChevronRight size={16}/></button> : <button className="primary" disabled={busy || disabled || done} onClick={() => void confirm()}>{busy ? <LoaderCircle className="spin" size={16}/> : <CheckCircle2 size={16}/>} 确认并版本化</button>}</div></section></section>;
}
