/** 中文 ECOMIC 科研工作台；所有状态变更只能经过 typed RPC。 */
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const SESSION_KEY = Symbol.for("ecomic.active-session-id");
const currentSession = () => (globalThis as Record<symbol, string | undefined>)[SESSION_KEY];
const setSession = (value: string | undefined) => { (globalThis as Record<symbol, string | undefined>)[SESSION_KEY] = value; };
// Windows clipboard text can contain isolated UTF-16 surrogates; replace only those,
// keeping ordinary Chinese and valid emoji intact before Node encodes the RPC as UTF-8.
const sanitizeForUtf8 = (value: string) => value.replace(/(?:[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF])/g, "�");
const rpcInput = (action: string, payload: Record<string, unknown>) => `${JSON.stringify({ action, payload }, (_key, value) => typeof value === "string" ? sanitizeForUtf8(value) : value)}\n`;
function rpc(action: string, payload: Record<string, unknown>) { const result = spawnSync(process.env.ECOMIC_PYTHON || "python", ["-m", "agent_backend.rpc"], { cwd: root, input: rpcInput(action, payload), encoding: "utf8", windowsHide: true }); if (result.error) throw result.error; const output = JSON.parse(result.stdout.trim().split(/\r?\n/).pop() || "{}"); if (output.status === "ERROR") throw new Error(output.message || "ResearchRuntime 调用失败"); return output; }
function safeError(error: unknown) { return sanitizeForUtf8(String((error as { message?: string })?.message || error || "未知错误")).replace(/(Bearer\s+)[^\s]+/gi, "$1[REDACTED]").replace(/(api[_-]?key|token)\s*[:=]\s*[^\s,;]+/gi, "$1=[REDACTED]"); }
async function ask(ctx: any, title: string, placeholder = "") { const answer = await ctx.ui.input(title, placeholder); return answer === undefined ? undefined : sanitizeForUtf8(answer).trim(); }
function renderHome(ctx: any) { ctx.ui.setWidget("ecomic-home", ["╔════════════════════ ECOMIC ════════════════════╗", "║ 跨领域选择性标签科研智能体 · SQLite 持久化 · Oracle 隔离 ║", "╠══════════════════════════════════════════════════╣", `║ 当前 Session：${currentSession() || "未开始"}`, "║ /ecomic-new-research  导入数据并确认语义", "║ /ecomic-run           创建假设并运行可审计策略", "║ /ecomic-final         锁定计划并执行内部最终评价", "║ /ecomic-history       恢复历史研究", "║ /ecomic-report        导出中文科研报告", "║ /ecomic-settings      模型与 API 设置", "║ /ecomic-test-connection  真实连接与工具调用测试", "║ /ecomic-scientist     启动受控 Scientist Agent", "╚══════════════════════════════════════════════════╝"], { placement: "aboveEditor" }); }
export default function (pi: ExtensionAPI) {
  pi.on("session_start", async (event, ctx) => { ctx.ui.setTitle("ECOMIC · 选择性标签科研智能体"); ctx.ui.setStatus("ecomic", `科研工作台 · ${event.reason === "new" ? "新研究" : "已恢复"} · Oracle LOCKED 🔒`); renderHome(ctx); });
  pi.registerCommand("ecomic-home", { description: "显示 ECOMIC 中文科研工作台", handler: async (_args, ctx) => renderHome(ctx) });
  pi.registerCommand("ecomic-new-research", { description: "导入 CSV/Parquet，并逐项确认选择性标签语义", handler: async (_args, ctx) => { try {
    const file = await ask(ctx, "导入结构化数据集", "CSV 或 Parquet 的绝对路径"); if (!file) return;
    const description = await ask(ctx, "选择性标签业务语义", "什么历史决策决定后续结果是否可见？"); const created: any = rpc("load_dataset", { path: file, description: description || "" }); setSession(created.session_id); const inferred = created.domain_spec || {};
    const decision = await ask(ctx, "确认历史决策字段", inferred.historical_decision?.column || ""); const target = await ask(ctx, "确认结果标签字段", inferred.outcome?.column || ""); const cost = await ask(ctx, "确认观察成本字段（可选）", inferred.observation_cost?.column || "");
    const observed = await ask(ctx, "哪些决策值表示可获得后续标签？", "以逗号分隔，例如 yes,approved"); const hidden = await ask(ctx, "哪些决策值表示标签隐藏？", "以逗号分隔，例如 no,rejected"); const decisionTime = await ask(ctx, "历史决策时间字段（可选）", ""); const outcomeTime = await ask(ctx, "结果发生时间字段（可选）", "");
    if (!decision || !target || !observed || !hidden) { ctx.ui.notify("关键映射尚未完成；Session 已安全保存，可通过 /ecomic-history 继续。", "warning"); return; }
    rpc("confirm_decision_mapping", { session_id: currentSession(), decision_column: decision, target_column: target, cost_column: cost || undefined, observed_values: observed.split(",").map((x) => x.trim()).filter(Boolean), non_observed_values: hidden.split(",").map((x) => x.trim()).filter(Boolean), decision_time: decisionTime || undefined, outcome_time: outcomeTime || undefined });
    const reversible = await ctx.ui.confirm("确认观察动作", "该观察/离线回放动作是否可逆？"); const simulatable = await ctx.ui.confirm("确认观察动作", "该动作是否能由当前数据安全模拟？"); const actionDescription = await ask(ctx, "观察动作说明", "例如：离线重放历史记录，不触发真实业务动作。"); const approved: any = rpc("confirm_observation_action", { session_id: currentSession(), reversible, simulatable, description: actionDescription || "" });
    ctx.ui.setStatus("ecomic", `ECOMIC · Session ${String(currentSession()).slice(-8)} · ${approved.audit?.status || "已映射"}`); ctx.ui.notify(`语义审计：${approved.audit?.status || "已完成"}。`, approved.audit?.status === "BLOCKED" ? "error" : "info"); renderHome(ctx);
  } catch (error) { ctx.ui.notify(`研究初始化失败：${safeError(error)}`, "error"); } } });
  pi.registerCommand("ecomic-run", { description: "创建假设、实验计划，并运行真实动态选择策略", handler: async (_args, ctx) => { try {
    const sessionId = currentSession(); if (!sessionId) { ctx.ui.notify("请先新建研究，或通过 /ecomic-history 恢复研究。", "warning"); return; } const question = await ask(ctx, "研究问题 / 假设", "例如：低预算下不确定性优先是否优于数量优先？"); if (!question) return; const policy = await ctx.ui.select("选择策略", ["LRBE-Uncertainty", "Random", "CountOnly-MinCost"]); if (!policy) return; const budget = Number(await ask(ctx, "预算", "30")); const rounds = Number(await ask(ctx, "轮数", "3")); if (!(budget > 0) || !(rounds >= 1)) throw new Error("预算必须大于 0，轮数至少为 1。");
    const hypothesis: any = rpc("create_hypothesis", { session_id: sessionId, content: question }); const plan: any = rpc("plan_experiment", { session_id: sessionId, hypothesis_id: hypothesis.hypothesis_id, policy, budget, rounds }); const run: any = rpc("run_experiment", { session_id: sessionId, plan_id: plan.plan_id, policy, budget, seed: 7, rounds }); ctx.ui.setWidget("ecomic-workbench", [`研究 Session：${sessionId}`, `策略：${policy}`, `Run：${run.run_id}`, `完成轮数：${run.observations?.length || 0}`, "Oracle：LOCKED 🔒（最终评估前不可见）"], { placement: "aboveEditor" }); ctx.ui.notify(`实验 ${run.run_id} 已完成并持久化到 SQLite。`, "info");
  } catch (error) { ctx.ui.notify(`实验失败：${safeError(error)}`, "error"); } } });
  pi.registerCommand("ecomic-final", { description: "锁定最近运行所属计划，并执行 evaluator-owned 最终评价", handler: async (_args, ctx) => { try { const sessionId = currentSession(); if (!sessionId) throw new Error("当前没有活动 Session。"); const snapshot: any = rpc("resume_environment", { session_id: sessionId }); if (!snapshot.run_id) throw new Error("当前 Session 没有可恢复的实验 Run。"); rpc("lock_run_plan", { session_id: sessionId, run_id: snapshot.run_id }); const final: any = rpc("finalize_evaluation", { session_id: sessionId, run_id: snapshot.run_id }); ctx.ui.notify(`最终评价完成：${final.status}。最终指标仅由内部 Evaluator 计算。`, "info"); } catch (error) { ctx.ui.notify(`最终评价失败：${safeError(error)}`, "error"); } } });
  pi.registerCommand("ecomic-report", { description: "从 SQLite source of truth 导出中文科研报告", handler: async (_args, ctx) => { try { const sessionId = currentSession(); if (!sessionId) throw new Error("当前没有活动 Session。"); const report: any = rpc("generate_report", { session_id: sessionId }); ctx.ui.notify(`报告已导出：${report.final_report}`, "info"); } catch (error) { ctx.ui.notify(`报告导出失败：${safeError(error)}`, "error"); } } });
}
