/** Chinese Pi workbench: all state-changing actions go through typed RPC. */
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."); let activeSession:string|undefined;
function rpc(action:string,payload:Record<string,unknown>){const r=spawnSync(process.env.ECOMIC_PYTHON||"python",["-m","agent_backend.rpc"],{cwd:root,input:`${JSON.stringify({action,payload})}\n`,encoding:"utf8",windowsHide:true});if(r.error)throw r.error;return JSON.parse(r.stdout.trim().split(/\r?\n/).pop()||"{}");}
function displayError(value:any){const text=String(value?.message||value?.reason||"未知错误");if(/401/.test(text))return "API Key 无效或没有权限";if(/404/.test(text))return "模型或 API Base URL 不存在";if(/429/.test(text))return "请求频率或额度受限";if(/timeout/i.test(text))return "网络连接超时";return text.replace(/(Bearer\s+)[^\s]+/gi,"$1[REDACTED]");}
async function ask(ctx:any,title:string,placeholder=""){const v=await ctx.ui.input(title,placeholder);return v?.trim();}
export default function(pi:ExtensionAPI){
 pi.registerCommand("ecomic-new-research",{description:"开始新的 ECOMIC 研究（中文工作台）",handler:async(_args,ctx)=>{try{const file=await ask(ctx,"导入结构化数据集","CSV 或 Parquet 绝对路径");if(!file)return;const description=await ask(ctx,"数据与标签可见性说明","例如：复核决定是否能获得后续标签");const created:any=rpc("load_dataset",{path:file,description:description||""});if(created.status==="ERROR")throw created;activeSession=created.session_id;ctx.ui.setStatus("ecomic",`ECOMIC · Session ${activeSession.slice(-8)} · 需要确认语义`);const spec=created.domain_spec;const decision=await ask(ctx,"确认历史决策字段",spec.historical_decision?.column||"");const target=await ask(ctx,"确认结果标签字段",spec.outcome?.column||"");const cost=await ask(ctx,"确认观察成本字段（可选）",spec.observation_cost?.column||"");const observed=await ask(ctx,"哪些决策值表示可获得后续标签？","以逗号分隔，例如 yes,approved");const hidden=await ask(ctx,"哪些决策值表示标签隐藏？","以逗号分隔，例如 no,rejected");const dt=await ask(ctx,"决策时间字段","");const ot=await ask(ctx,"结果时间字段","");if(!decision||!target||!observed||!hidden){ctx.ui.notify("关键字段未确认；Session 已保存，可稍后继续。","warning");return;}const confirmed:any=rpc("confirm_decision_mapping",{session_id:activeSession,decision_column:decision,target_column:target,cost_column:cost||undefined,observed_values:observed.split(",").map(x=>x.trim()).filter(Boolean),non_observed_values:hidden.split(",").map(x=>x.trim()).filter(Boolean),decision_time:dt||undefined,outcome_time:ot||undefined,observation_reversible:true,observation_simulatable:true});ctx.ui.notify(`语义审计：${confirmed.audit.status}。${confirmed.audit.status==="BLOCKED"?"请修正时间或映射后再实验。":"可以创建研究假设。"}`,confirmed.audit.status==="BLOCKED"?"error":"info");}catch(error){ctx.ui.notify(`研究初始化失败：${displayError(error)}`,"error");}}});
 pi.registerCommand("ecomic-run",{description:"从当前 Session 创建假设、运行实验并锁定评价",handler:async(_args,ctx)=>{try{if(!activeSession){ctx.ui.notify("请先执行 /ecomic-new-research。","warning");return;}const state:any=rpc("observe_state",{session_id:activeSession});const question=await ask(ctx,"研究问题 / 假设","例如：低预算下不确定性优先是否优于数量优先？");if(!question)return;const hypothesis:any=rpc("create_hypothesis",{session_id:activeSession,content:question});const policy=await ask(ctx,"策略","LRBE-Uncertainty / Random / CountOnly-MinCost")||"LRBE-Uncertainty";const budget=Number(await ask(ctx,"预算","30"));const rounds=Number(await ask(ctx,"轮数","3"));const plan:any=rpc("plan_experiment",{session_id:activeSession,hypothesis_id:hypothesis.hypothesis_id,policy,budget,rounds});const run:any=rpc("run_experiment",{session_id:activeSession,plan_id:plan.plan_id,policy,budget,seed:7,rounds});ctx.ui.setWidget("ecomic-workbench",[`ECOMIC 研究工作台`,`Session: ${activeSession}`,`策略: ${policy} · 完成轮数: ${run.observations?.length||0}`,`Oracle: LOCKED 🔒 · 当前状态: ${state.status}`,"使用 /ecomic-final 执行锁定后的内部最终评价。"],{placement:"aboveEditor"});ctx.ui.notify(`实验完成，Run：${run.run_id}`,"info");}catch(error){ctx.ui.notify(`实验失败：${displayError(error)}`,"error");}}});
 pi.registerCommand("ecomic-final",{description:"锁定计划并执行内部 Oracle 最终评价",handler:async(_args,ctx)=>{try{if(!activeSession){ctx.ui.notify("没有当前 Session。","warning");return;}const state:any=rpc("observe_state",{session_id:activeSession});if(!state.runs){ctx.ui.notify("尚无实验 Run。","warning");return;}const resumed:any=rpc("resume_environment",{session_id:activeSession});const runId=resumed.run_id;const planId=(await ask(ctx,"输入要锁定的 Plan ID","从 /ecomic-run 的记录获取"));if(!planId)return;rpc("lock_research_plan",{session_id:activeSession,plan_id:planId});const final:any=rpc("finalize_evaluation",{session_id:activeSession,run_id:runId});ctx.ui.notify(`最终评价完成：${final.status}。指标由内部 Oracle 计算。","info");}catch(error){ctx.ui.notify(`最终评价失败：${displayError(error)}`,"error");}}});
 pi.registerCommand("ecomic-home",{description:"显示 ECOMIC 中文主界面状态",handler:async(_args,ctx)=>{ctx.ui.setWidget("ecomic-home",["╔════════════════ ECOMIC ════════════════╗","║ 跨领域选择性标签科研智能体              ║",`║ 当前 Session：${activeSession||"未开始"}`,"║ /ecomic-new-research 开始新的研究       ║","║ /ecomic-run 运行研究实验               ║","║ /ecomic-final 内部 Oracle 最终评价      ║","║ /ecomic-settings 模型与 API 设置        ║","╚══════════════════════════════════════════╝"],{placement:"aboveEditor"});ctx.ui.notify("ECOMIC 工作台已显示。","info");}});
}
