import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Type } from "@earendil-works/pi-ai";
import { defineTool, type ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Key, matchesKey } from "@earendil-works/pi-tui";
import { PROVIDERS, checkConfiguration, loadNonSecretConfig, redactSecret, saveCredential, saveNonSecretConfig } from "./settings.mjs";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
function callRuntime(action:string,params:Record<string,unknown>){const r=spawnSync(process.env.ECOMIC_PYTHON||"python",["-m","agent_backend.rpc"],{cwd:root,input:`${JSON.stringify({action,payload:params})}\n`,encoding:"utf8",windowsHide:true});if(r.error)throw r.error;return JSON.parse(r.stdout.trim().split(/\r?\n/).pop()||"{}");}
async function secretInput(ctx:any,title:string){return ctx.ui.custom<string|null>((tui:any,theme:any,_kb:any,done:any)=>{let value="";return {render:(width:number)=>[theme.fg("accent",`╔═ ${title} ═╗`),"",theme.fg("text",`  ${"*".repeat(value.length)}`),"",theme.fg("dim","  Enter 确认 · Esc 取消（密钥不会回显或写入日志）"),theme.fg("accent","╚"+"═".repeat(Math.max(1,width-1)))],handleInput:(data:string)=>{if(matchesKey(data,Key.enter))return done(value);if(matchesKey(data,Key.escape))return done(null);if(matchesKey(data,Key.backspace)){value=value.slice(0,-1);tui.requestRender();return;}if(data.length===1&&data>=" "){value+=data;tui.requestRender();}},invalidate:()=>{}};});}
export default function(pi:ExtensionAPI){
 const session=Type.Object({session_id:Type.String(),state_dir:Type.Optional(Type.String())}); const register=(name:string,parameters:any)=>pi.registerTool(defineTool({name:`ecomic_${name}`,label:`ECOMIC: ${name}`,description:"ECOMIC typed research tool. Oracle labels and final metrics are never agent supplied.",parameters,async execute(_id,params){const result=callRuntime(name,params as Record<string,unknown>);return {content:[{type:"text",text:JSON.stringify(result,null,2)}],details:{action:name,result}};}}));
 register("load_dataset",Type.Object({path:Type.String(),description:Type.Optional(Type.String()),state_dir:Type.Optional(Type.String())}));
 register("confirm_decision_mapping",Type.Object({...session.properties,decision_column:Type.String(),observed_values:Type.Array(Type.String()),non_observed_values:Type.Array(Type.String()),target_column:Type.Optional(Type.String()),cost_column:Type.Optional(Type.String()),decision_time:Type.Optional(Type.String()),outcome_time:Type.Optional(Type.String()),observation_reversible:Type.Boolean(),observation_simulatable:Type.Boolean()}));
 register("create_hypothesis",Type.Object({...session.properties,content:Type.String()})); register("plan_experiment",Type.Object({...session.properties,hypothesis_id:Type.String(),policy:Type.String(),budget:Type.Number(),rounds:Type.Integer({minimum:1})})); register("run_experiment",Type.Object({...session.properties,plan_id:Type.String(),policy:Type.String(),budget:Type.Number(),seed:Type.Integer(),rounds:Type.Integer({minimum:1})})); register("lock_research_plan",Type.Object({...session.properties,plan_id:Type.String()})); register("finalize_evaluation",Type.Object({...session.properties,run_id:Type.String()})); register("observe_state",session); register("claim_guard",Type.Object({...session.properties,claim:Type.String(),evidence_run_ids:Type.Array(Type.String()),strength:Type.Optional(Type.String())}));
 pi.registerCommand("ecomic-settings",{description:"模型与 API 设置（中文、安全凭据）",handler:async(_args,ctx)=>{const choices=Object.entries(PROVIDERS).map(([id,p])=>`${id} · ${p.label}`);const chosen=await ctx.ui.select("模型服务商",choices);if(!chosen)return;const provider=chosen.split(" · ")[0];const current=loadNonSecretConfig();const model=await ctx.ui.input("模型 ID",current.model||"例如 deepseek-chat");if(!model)return;const base=await ctx.ui.input("API Base URL（留空使用默认）",current.base_url||"");const key=await secretInput(ctx,`${PROVIDERS[provider].label} API Key`);if(key===null)return;const check=checkConfiguration({provider,model,base_url:base||null},key);if(!check.ok){ctx.ui.notify(`配置未通过：${check.message}`,"error");return;}const persist=await ctx.ui.confirm("保存凭据",`仅本次会话使用？选择“否”将保存到 ~/.ecomic/credentials.env。\n当前 Key：${redactSecret(key)}`);saveNonSecretConfig({provider,model,base_url:base||null});if(!persist){process.env[PROVIDERS[provider].keyEnv]=key;ctx.ui.notify("已仅在当前 Pi 进程内配置 API Key。","info");}else{saveCredential(provider,key);ctx.ui.notify("已保存到本机私有凭据文件，未写入项目或数据库。","info");}}});
}
