import fs from "node:fs";
import os from "node:os";
import path from "node:path";
export const PROVIDERS=Object.freeze({openai:{label:"OpenAI",keyEnv:"OPENAI_API_KEY",toolCalling:true},anthropic:{label:"Anthropic",keyEnv:"ANTHROPIC_API_KEY",toolCalling:true},deepseek:{label:"DeepSeek",keyEnv:"DEEPSEEK_API_KEY",toolCalling:true},google:{label:"Google Gemini",keyEnv:"GOOGLE_API_KEY",toolCalling:true},openrouter:{label:"OpenRouter",keyEnv:"OPENROUTER_API_KEY",toolCalling:"unknown"},custom_openai_compatible:{label:"自定义 OpenAI-Compatible",keyEnv:"ECOMIC_CUSTOM_API_KEY",toolCalling:"unknown"}});
export const ecomicHome=(home=os.homedir())=>path.join(home,".ecomic"); export const configPath=home=>path.join(ecomicHome(home),"config.json"); export const credentialsPath=home=>path.join(ecomicHome(home),"credentials.env");
export function redactSecret(value){const text=String(value??"");return !text?"未配置":text.length<=6?"******":`${text.slice(0,3)}****${text.slice(-4)}`;}
export function redactText(value){return String(value??"").replace(/(authorization\s*:\s*bearer\s+)[^\s,;]+/gi,"$1[REDACTED]").replace(/((?:api[_-]?key|token)\s*[:=]\s*)[^\s,;]+/gi,"$1[REDACTED]");}
function ensure(home){fs.mkdirSync(ecomicHome(home),{recursive:true,mode:0o700});}
export function loadNonSecretConfig(home){try{return JSON.parse(fs.readFileSync(configPath(home),"utf8"));}catch{return {provider:"mock",model:null,base_url:null,language:"zh-CN",thinking_level:"normal"};}}
export function saveNonSecretConfig(config,home){ensure(home);const safe={provider:config.provider,model:config.model||null,base_url:config.base_url||null,language:config.language||"zh-CN",thinking_level:config.thinking_level||"normal"};fs.writeFileSync(configPath(home),`${JSON.stringify(safe,null,2)}\n`,{encoding:"utf8",mode:0o600});return safe;}
export function saveCredential(provider,apiKey,home){const definition=PROVIDERS[provider];if(!definition)throw new Error("不支持的 Provider");if(!apiKey||/\r|\n/.test(apiKey))throw new Error("API Key 不能为空且不能包含换行");ensure(home);fs.writeFileSync(credentialsPath(home),`${definition.keyEnv}=${apiKey}\n`,{encoding:"utf8",mode:0o600});try{fs.chmodSync(credentialsPath(home),0o600);}catch{}return {provider,masked_key:redactSecret(apiKey),stored:"local-private-file"};}
export function clearCredential(home){try{fs.rmSync(credentialsPath(home));return true;}catch{return false;}}
export function checkConfiguration(config,apiKey){const p=PROVIDERS[config.provider];if(!p)return {ok:false,message:"当前 Provider 不在 ECOMIC 已声明的 Pi 配置范围内"};if(config.base_url&&!/^https?:\/\//i.test(config.base_url))return {ok:false,message:"API Base URL 必须以 http:// 或 https:// 开头"};if(config.provider!=="mock"&&!apiKey)return {ok:false,message:"尚未输入 API Key"};if(!config.model)return {ok:false,message:"尚未填写 Model ID"};if(p.toolCalling!==true)return {ok:false,message:"该 Provider 的 Tool Calling 能力尚未在当前 Pi runtime 中验证，不能启动正式 Scientist Agent"};return {ok:true,message:"配置格式有效；真实连接测试会产生少量 Token 消耗",toolCalling:true};}
